djlab:
  jupyter_server:
    display_filepath: '/home/README.md'
    password: 'datajoint'
    save_output: 'FALSE'
djlabhub:
  server_name: 'NULL'
  notebook_repo:
    target: 'NULL'
    subpath: '.'