name: singleuser-relase
on:
  workflow_dispatch:
    inputs:
      jupyterhub_version:
        required: true
        default: '4.0.2'
        type: choice
        options:
          - '5.0.0'
          - '4.0.2'
          - '1.4.2'

jobs:
  release-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # following python version end of life: https://devguide.python.org/versions/
          - py_ver: '3.11'
          - py_ver: '3.10'
          - py_ver: '3.9'
          - py_ver: '3.8'
    env:
      PY_VER: ${{matrix.py_ver}}
      JUPYTERHUB_VER: ${{github.event.inputs.jupyterhub_version}}
    steps:
      - uses: actions/checkout@
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - run: |
          cd singleuser
          docker compose build
          export IMAGE_TAG=$(eval "echo \"$(cat docker-compose.yaml | grep image: | awk '{ print $2 }' | grep singleuser)\"")
          docker push $IMAGE_TAG
